/* eslint-disable @next/next/no-html-link-for-pages -- vinext 1.0.0-beta.2 currently throws while hydrating next/link. */
import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { ExternalMedia } from "../../components/ExternalMedia";
import { reservedTalentSlugs } from "../../db/schema";
import { getPublishedBySlug } from "../../lib/cms-public";

type Props = { params: Promise<{ slug: string }> };
type MediaItem = { url?: string; title?: string; category?: string; visible?: boolean };
type ContactItem = { value?: string; visible?: boolean };
type PublicContact = { key: string; label: string; value: string; kind: "email" | "phone" | "url" };
export const dynamic = "force-dynamic";
function strings(value: unknown): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
function media(value: unknown): MediaItem[] { return Array.isArray(value) ? value.filter((item): item is MediaItem => Boolean(item && typeof item === "object" && (item as MediaItem).url && (item as MediaItem).visible !== false)) : []; }
function descriptions(value: unknown, keys: string[]): string[] { return Array.isArray(value) ? value.map((item) => { if (typeof item === "string") return item; if (!item || typeof item !== "object") return ""; const record = item as Record<string, unknown>; return keys.map((key) => typeof record[key] === "string" ? record[key] : "").filter(Boolean).join(" · "); }).filter(Boolean) : []; }
function publicContact(value: unknown): PublicContact[] { if (!value || typeof value !== "object" || Array.isArray(value)) return []; const source=value as Record<string,unknown>; const labels:Record<string,string>={email:"Email",phone:"Teléfono",instagram:"Instagram",linkedin:"LinkedIn",website:"Web"}; const standard=Object.entries(labels).flatMap(([key,label])=>{const item=source[key] as ContactItem|undefined;return item?.visible===true&&item.value?[{key,label,value:item.value,kind:key==="email"?"email" as const:key==="phone"?"phone" as const:"url" as const}]:[];}); const other=Array.isArray(source.other)?source.other.flatMap((item,index)=>{if(!item||typeof item!=="object")return[];const entry=item as Record<string,unknown>;return entry.visible!==false&&typeof entry.value==="string"&&entry.value?[{key:`other-${index}`,label:String(entry.label??"Enlace"),value:entry.value,kind:"url" as const}]:[];}):[]; return [...standard,...other]; }
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params; if (reservedTalentSlugs.has(slug)) return {}; const record = await getPublishedBySlug("talents", slug); if (!record) return {};
  const data = record.data; const name = String(data.stageName ?? data.name ?? "Talento"); const title = String(data.seoTitle ?? `${name} | ${data.professionalTitle ?? "Talento de doblaje"} | MASTER DUB`); const description = String(data.seoDescription ?? data.introduction ?? ""); const image = String(data.socialImage ?? data.photo ?? "");
  return { title, description, alternates: { canonical: `/${slug}` }, openGraph: { title, description, type: "profile", images: image ? [image] : [] }, twitter: { card: image ? "summary_large_image" : "summary", title, description, images: image ? [image] : [] } };
}
export default async function TalentPage({ params }: Props) {
  const { slug } = await params; if (reservedTalentSlugs.has(slug)) notFound(); const record = await getPublishedBySlug("talents", slug); if (!record) notFound(); const data = record.data;
  const demos = media(data.demos), videos = media(data.videos), creditRecords = Array.isArray(data.credits) ? data.credits.filter((item): item is Record<string,unknown> => Boolean(item && typeof item === "object")) : [], credits = descriptions(data.credits,["title","project","role","year","description"]), training = descriptions(data.training,["center","description","dates"]), specialties = strings(data.specialties), languages = strings(data.languages), accents = strings(data.accents), gallery = strings(data.gallery); const contact = publicContact(data.contact); const hasVoice = Boolean(data.voiceCharacteristics) || Boolean(data.voiceAgeRange) || languages.length > 0 || accents.length > 0 || specialties.length > 0;
  const sections = [{ id: "perfil", label: "Perfil", show: true }, { id: "voz", label: "Voz", show: hasVoice }, { id: "demos", label: "Demos", show: demos.length > 0 }, { id: "videos", label: "Vídeos", show: videos.length > 0 }, { id: "trabajos", label: "Trabajos", show: credits.length > 0 }, { id: "formacion", label: "Formación", show: training.length > 0 }, { id: "galeria", label: "Galería", show: gallery.length > 0 }, { id: "contacto", label: "Contacto", show: contact.length > 0 }].filter((item) => item.show);
  const template = ["cinema","editorial","studio"].includes(String(data.template)) ? String(data.template) : "editorial";
  return <main className={`talent-page talent-template-${template}`} style={{ "--talent-overlay": String(data.backgroundIntensity ?? .58) } as React.CSSProperties}>
    <nav className="talent-nav"><a href="/talentos">MASTER DUB</a><div>{sections.map((item) => <a href={`#${item.id}`} key={item.id}>{item.label}</a>)}</div></nav>
    <section className="talent-hero" id="perfil">{Boolean(data.backgroundImage) && <Image className="talent-background" src={String(data.backgroundImage)} alt="" fill priority sizes="100vw" style={{ objectPosition: String(data.photoPosition ?? "center") }} />}<div className="talent-overlay" /><div className="talent-hero-inner">{Boolean(data.photo) && <figure><Image src={String(data.photo)} alt={String(data.photoAlt ?? data.name ?? "")} fill priority sizes="(max-width: 760px) 88vw, 40vw" style={{ objectPosition: String(data.photoPosition ?? "center") }} /></figure>}<div><p>Talentos MASTER DUB</p><h1>{String(data.stageName ?? data.name ?? "")}</h1>{Boolean(data.professionalTitle) && <h2>{String(data.professionalTitle)}</h2>}{Boolean(data.location) && <span>{String(data.location)}</span>}{Boolean(data.introduction) && <strong>{String(data.introduction)}</strong>}</div></div></section>
    <div className="talent-content">{Boolean(data.biography) && <section><p className="talent-kicker">Perfil</p><h2>Sobre mí</h2><p>{String(data.biography)}</p></section>}
      {hasVoice && <section id="voz"><p className="talent-kicker">Voz</p><h2>Características</h2><dl>{Boolean(data.voiceCharacteristics) && <div><dt>Voz</dt><dd>{String(data.voiceCharacteristics)}</dd></div>}{Boolean(data.voiceAgeRange) && <div><dt>Rango</dt><dd>{String(data.voiceAgeRange)}</dd></div>}{languages.length > 0 && <div><dt>Idiomas</dt><dd>{languages.join(" · ")}</dd></div>}{accents.length > 0 && <div><dt>Acentos</dt><dd>{accents.join(" · ")}</dd></div>}{specialties.length > 0 && <div><dt>Especialidades</dt><dd>{specialties.join(" · ")}</dd></div>}</dl></section>}
      {demos.length > 0 && <section id="demos"><p className="talent-kicker">Audio</p><h2>Demos</h2><div className="talent-media-grid">{demos.map((item,index) => <article key={index}><ExternalMedia url={item.url!} title={item.title ?? `Demo ${index+1}`} />{Boolean(item.category) && <small>{item.category}</small>}{Boolean((item as Record<string,unknown>).description) && <p>{String((item as Record<string,unknown>).description)}</p>}</article>)}</div></section>}
      {videos.length > 0 && <section id="videos"><p className="talent-kicker">Imagen</p><h2>Vídeos</h2><div className="talent-media-grid">{videos.map((item,index) => <article key={index}><ExternalMedia url={item.url!} title={item.title ?? `Vídeo ${index+1}`} />{Boolean(item.category) && <small>{item.category}</small>}{Boolean((item as Record<string,unknown>).description) && <p>{String((item as Record<string,unknown>).description)}</p>}</article>)}</div></section>}
      {credits.length > 0 && <section id="trabajos"><p className="talent-kicker">Trayectoria</p><h2>Trabajos</h2><ul>{credits.map((item,index) => <li key={`${item}-${index}`}>{typeof creditRecords[index]?.url === "string" && creditRecords[index].url ? <a href={String(creditRecords[index].url)} target="_blank" rel="noreferrer">{item} ↗</a> : item}</li>)}</ul></section>}
      {training.length > 0 && <section id="formacion"><p className="talent-kicker">Formación</p><h2>Formación</h2><ul>{training.map((item) => <li key={item}>{item}</li>)}</ul></section>}
      {gallery.length > 0 && <section id="galeria"><p className="talent-kicker">Galería</p><h2>Imágenes</h2><div className="talent-gallery">{gallery.map((src,index)=><figure key={src}><Image src={src} alt={`Galería de ${String(data.stageName ?? data.name ?? "talento")} · imagen ${index+1}`} fill sizes="(max-width: 760px) 100vw, 45vw" /></figure>)}</div></section>}
      {contact.length > 0 && <section id="contacto"><p className="talent-kicker">Contacto</p><h2>Contacto profesional</h2><div className="talent-contact">{contact.map((item) => <a key={item.key} href={item.kind === "email" ? `mailto:${item.value}` : item.kind === "phone" ? `tel:${item.value}` : item.value} target={item.kind === "url" ? "_blank" : undefined} rel="noreferrer">{item.label}</a>)}</div></section>}
    </div><footer className="talent-footer"><a href="/">Talentos MASTER DUB · Formación profesional de doblaje</a></footer>
  </main>;
}
