"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { useCallback, useEffect, useMemo, useState } from "react";
import { MediaLibrary } from "./MediaLibrary";
import { RecordEditor } from "./RecordEditor";
import { cmsApi, type Activity, type AdminSection, type CmsRecord, recordStateLabel, recordTitle } from "./types";

const nav: Array<{ id: AdminSection; label: string; icon: string }> = [
  { id: "dashboard", label: "Inicio", icon: "⌂" }, { id: "web", label: "Web", icon: "▤" },
  { id: "talents", label: "Talentos", icon: "◉" }, { id: "professionals", label: "Profesionales", icon: "◇" },
  { id: "news", label: "Noticias", icon: "▧" }, { id: "media", label: "Multimedia", icon: "▣" },
  { id: "settings", label: "Ajustes", icon: "⚙" }, { id: "trash", label: "Papelera", icon: "⌫" },
];

export function AdminDashboard() {
  const [section, setSection] = useState<AdminSection>("dashboard");
  const [records, setRecords] = useState<CmsRecord[]>([]);
  const [activity, setActivity] = useState<Activity[]>([]);
  const [actor, setActor] = useState("");
  const [state, setState] = useState<"loading" | "ready" | "auth" | "setup" | "error">("loading");
  const [message, setMessage] = useState("");
  const [editing, setEditing] = useState<CmsRecord | null>(null);
  const [mobileOpen, setMobileOpen] = useState(false);
  const load = useCallback(async () => {
    setState("loading");
    try { const result = await cmsApi("bootstrap"); setRecords(result.records); setActivity(result.activity); setActor(result.actor); setState("ready"); }
    catch (error) { const status=(error as {status?:number}).status; const code=(error as {result?:{code?:string}}).result?.code; if(status===401||status===403)setState("auth");else if(code==="CMS_STORAGE_NOT_CONFIGURED"||code==="ADMIN_NOT_CONFIGURED")setState("setup");else setState("error"); }
  }, []);
  useEffect(() => { const timer=window.setTimeout(()=>void load(),0); return()=>window.clearTimeout(timer); },[load]);
  const visibleRecords = useMemo(() => { if(section==="trash")return records.filter((record)=>record.status==="trashed"); const collection=({web:"home",talents:"talents",professionals:"professionals",news:"news",media:"media",settings:"settings"} as Record<string,string>)[section]; return collection?records.filter((record)=>record.collection===collection&&record.status!=="trashed"):[]; },[records,section]);
  const media = records.filter((record)=>record.collection==="media"&&record.status!=="trashed");
  function choose(next:AdminSection){setSection(next);setMobileOpen(false);}
  async function seed(){setMessage("Preparando contenido actual…");try{await cmsApi("seed",{method:"POST",body:"{}"});await load();setMessage("Contenido inicial preparado.");}catch(error){setMessage(error instanceof Error?error.message:"No se ha podido preparar el CMS.");}}
  async function action(record:CmsRecord,verb:"publish"|"trash"|"restore"|"permanent"){if((verb==="trash"||verb==="permanent")&&!window.confirm(verb==="trash"?"¿Enviar este contenido a la papelera?":"Esta eliminación es definitiva. ¿Continuar?"))return;try{await cmsApi(`${record.collection}/${record.id}/${verb}`,{method:verb==="permanent"?"DELETE":"POST",body:"{}"});await load();setMessage(verb==="trash"?"Contenido enviado a la papelera.":verb==="restore"?"Contenido restaurado.":verb==="permanent"?"Contenido eliminado.":"Contenido publicado.");}catch(error){setMessage(error instanceof Error?error.message:"No se ha podido completar la acción.");}}
  return <main className="admin-shell"><aside className={`admin-sidebar${mobileOpen?" is-open":""}`}><div className="admin-brand"><strong>MASTER DUB</strong><span>Administración</span></div><nav aria-label="Administración">{nav.map((item)=><button type="button" className={section===item.id?"is-active":""} onClick={()=>choose(item.id)} key={item.id}><i aria-hidden="true">{item.icon}</i>{item.label}</button>)}</nav><a className="admin-view-site" href="/" target="_blank">Ver web <span>↗</span></a></aside><div className="admin-workspace"><header className="admin-topbar"><button className="admin-menu-button" type="button" onClick={()=>setMobileOpen((open)=>!open)} aria-expanded={mobileOpen}>Menú</button><div><small>MASTER DUB</small><strong>{nav.find((item)=>item.id===section)?.label}</strong></div><span>{actor||"Administración"}</span></header><div className="admin-content">{message&&<p className="admin-flash" role="status">{message}<button type="button" onClick={()=>setMessage("")}>×</button></p>}{state==="loading"&&<AdminState title="Cargando administración…" />}{state==="auth"&&<AdminState title="Acceso protegido" text="Inicia sesión con la cuenta autorizada para administrar MASTER DUB." action={<>{/* SIWC requires top-level native navigation. */}<a href="/signin-with-chatgpt?return_to=/admin" target="_top" suppressHydrationWarning>Iniciar sesión</a></>} />}{state==="setup"&&<AdminState title="CMS pendiente de conectar" text="La interfaz está preparada. Falta activar los recursos de datos y la lista de administradores en Sites." />}{state==="error"&&<AdminState title="No se ha podido cargar el CMS" text="Comprueba la configuración y vuelve a intentarlo." action={<button type="button" onClick={()=>void load()}>Reintentar</button>} />}{state==="ready"&&records.length===0&&<AdminState title="Preparar contenido actual" text="Importa como punto de partida los textos, imágenes, profesionales y ajustes ya aprobados. No altera la web pública." action={<button type="button" onClick={()=>void seed()}>Inicializar CMS</button>} />}{state==="ready"&&records.length>0&&section==="dashboard"&&<Dashboard records={records} activity={activity} onNavigate={choose} />}{state==="ready"&&records.length>0&&section!=="dashboard"&&<CollectionView section={section} records={visibleRecords} onReload={load} onEdit={setEditing} onAction={action} onCreate={(collection)=>setEditing(newRecord(collection))} />}</div></div>{editing&&<RecordEditor record={editing} media={media} onClose={()=>setEditing(null)} onReload={load} onSaved={async()=>{setEditing(null);await load();}} />}</main>;
}

function AdminState({title,text,action}:{title:string;text?:string;action?:React.ReactNode}){return <section className="admin-state"><span>MASTER DUB</span><h1>{title}</h1>{text&&<p>{text}</p>}{action&&<div>{action}</div>}</section>;}
function Dashboard({records,activity,onNavigate}:{records:CmsRecord[];activity:Activity[];onNavigate:(section:AdminSection)=>void}){const count=(collection:string)=>records.filter((record)=>record.collection===collection&&record.status!=="trashed").length;return <><div className="admin-heading"><div><p>Panel de control</p><h1>MASTER DUB · Administración</h1></div><a href="/" target="_blank">Ver web ↗</a></div><div className="admin-metrics"><button type="button" onClick={()=>onNavigate("web")}><span>Web</span><strong>{count("home")}</strong><small>secciones editables</small></button><button type="button" onClick={()=>onNavigate("talents")}><span>Talentos</span><strong>{count("talents")}</strong><small>perfiles</small></button><button type="button" onClick={()=>onNavigate("professionals")}><span>Profesionales</span><strong>{count("professionals")}</strong><small>perfiles</small></button><button type="button" onClick={()=>onNavigate("news")}><span>Noticias</span><strong>{count("news")}</strong><small>publicaciones</small></button></div><section className="admin-panel"><header><div><p>Acciones rápidas</p><h2>Crear contenido</h2></div></header><div className="admin-quick-actions"><button type="button" onClick={()=>onNavigate("talents")}>＋ Talento</button><button type="button" onClick={()=>onNavigate("news")}>＋ Noticia</button><button type="button" onClick={()=>onNavigate("professionals")}>＋ Profesional invitado</button></div></section><section className="admin-panel"><header><div><p>Actividad</p><h2>Cambios recientes</h2></div></header>{activity.length?<ul className="admin-activity">{activity.map((item,index)=><li key={`${item.created_at}-${index}`}><span>{activityLabel(item.action)}</span><strong>{friendlyRecord(records,item.collection,item.record_id)}</strong><small>{item.actor_email} · {new Date(`${item.created_at}Z`).toLocaleString("es-ES")}</small></li>)}</ul>:<p className="admin-empty">Todavía no hay cambios registrados.</p>}</section></>;}
function activityLabel(action:string){return ({save_draft:"Borrador guardado",publish:"Publicado",upload:"Imagen subida",trash:"Enviado a papelera",restore:"Restaurado"} as Record<string,string>)[action]??"Actualizado";}
function friendlyRecord(records:CmsRecord[],collection:string,id:string){const found=records.find((record)=>record.collection===collection&&record.id===id);return found?recordTitle(found):"Contenido";}

function CollectionView({section,records,onReload,onEdit,onAction,onCreate}:{section:AdminSection;records:CmsRecord[];onReload:()=>Promise<void>;onEdit:(record:CmsRecord)=>void;onAction:(record:CmsRecord,action:"publish"|"trash"|"restore"|"permanent")=>void;onCreate:(collection:string)=>void}) {
  const collection=({web:"home",talents:"talents",professionals:"professionals",news:"news",media:"media",settings:"settings"} as Record<string,string>)[section];
  const canCreate=["talents","professionals","news"].includes(section);
  const card=(record:CmsRecord)=><article key={`${record.collection}-${record.id}`}><div className="admin-record-status"><span className={`is-${record.status}`}>{recordStateLabel(record)}{!record.visible?" · Oculto":""}</span>{record.protected&&<small>Protegido</small>}</div><h2>{recordTitle(record)}</h2><p>{String(record.draft.introduction??record.draft.description??record.draft.body??"Sin descripción")}</p><footer><button type="button" onClick={()=>onEdit(record)}>{section==="trash"?"Ver":"Editar"}</button>{record.status==="trashed"?<><button type="button" onClick={()=>onAction(record,"restore")}>Restaurar</button><button className="is-danger" type="button" onClick={()=>onAction(record,"permanent")}>Eliminar</button></>:<>{recordStateLabel(record)!=="Publicado"&&<button type="button" onClick={()=>onAction(record,"publish")}>Publicar</button>}{!record.protected&&<button className="is-danger" type="button" onClick={()=>onAction(record,"trash")}>Papelera</button>}</>}</footer></article>;
  const mainProfessionals=records.filter((record)=>record.draft.type!=="invitado");
  const invitedProfessionals=records.filter((record)=>record.draft.type==="invitado");
  return <><div className="admin-heading"><div><p>Contenido público</p><h1>{nav.find((item)=>item.id===section)?.label}</h1></div>{canCreate&&section!=="professionals"&&<button type="button" onClick={()=>onCreate(collection)}>＋ Nuevo</button>}</div>{section==="media"?<MediaLibrary records={records} onReload={onReload} onEdit={onEdit} onAction={onAction}/>:section==="professionals"?<><section className="admin-panel"><header><div><p>Equipo estable</p><h2>Profesionales principales</h2></div></header><div className="admin-records">{mainProfessionals.map(card)}</div></section><section className="admin-panel"><header><div><p>Equipo ampliado</p><h2>Profesionales invitados</h2></div><button type="button" onClick={()=>onCreate(collection)}>＋ Nuevo profesional invitado</button></header><div className="admin-records">{invitedProfessionals.length?invitedProfessionals.map(card):<p className="admin-empty">Todavía no hay profesionales invitados.</p>}</div></section></>:<div className="admin-records">{records.length===0?<p className="admin-empty">No hay contenido en esta vista.</p>:records.map(card)}</div>}</>;
}

function newRecord(collection:string):CmsRecord{return{id:crypto.randomUUID(),collection,slug:null,draft:collection==="talents"?{name:"",professionalTitle:"",template:"editorial",demos:[],videos:[],training:[],credits:[],gallery:[],contact:{}}:collection==="professionals"?{name:"",role:"",introduction:"",photo:"",photoAlt:"",website:null,links:[],type:"invitado"}:{title:"",introduction:"",body:"",gallery:[]},published:null,status:"draft",visible:true,order:0,protected:false,featured:false,listed:true,authorized:false,authorizationDate:null,updatedAt:new Date().toISOString(),publishedAt:null};}
