"use client";

/* eslint-disable @next/next/no-img-element */
import { useEffect, useMemo, useState } from "react";
import QRCode from "qrcode";
import { ExternalMedia } from "../ExternalMedia";
import { Field, FieldGroup, ObjectList, SelectField, StringList, Switch, TextArea } from "./fields";
import { ImagePicker } from "./MediaLibrary";
import { arrayValue, bool, cmsApi, type CmsData, type CmsRecord, labels, numberValue, objectValue, recordStateLabel, recordTitle, text } from "./types";

type Props = { record: CmsRecord; media: CmsRecord[]; onClose: () => void; onSaved: () => Promise<void> | void; onReload: () => Promise<void> };

function slugify(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 80); }
function imageSource(value: unknown) { return typeof value === "string" ? value : text(objectValue(value).src); }
function withImageSource(current: unknown, src: string) { return typeof current === "string" ? src : { ...objectValue(current), src }; }

export function RecordEditor({ record, media, onClose, onSaved, onReload }: Props) {
  const [data, setData] = useState<CmsData>({ ...record.draft });
  const [slug, setSlug] = useState(record.slug ?? "");
  const [visible, setVisible] = useState(record.visible);
  const [featured, setFeatured] = useState(record.featured);
  const [listed, setListed] = useState(record.listed);
  const [authorized, setAuthorized] = useState(record.authorized);
  const [authorizationDate, setAuthorizationDate] = useState(record.authorizationDate ?? "");
  const [order, setOrder] = useState(record.order);
  const [activeTab, setActiveTab] = useState("profile");
  const [feedback, setFeedback] = useState("");
  const [saving, setSaving] = useState(false);
  const [preview, setPreview] = useState(false);
  const [initialState] = useState(() => JSON.stringify({ data: record.draft, slug: record.slug ?? "", visible: record.visible, featured: record.featured, listed: record.listed, authorized: record.authorized, authorizationDate: record.authorizationDate ?? "", order: record.order }));
  const currentState = useMemo(() => JSON.stringify({ data, slug, visible, featured, listed, authorized, authorizationDate, order }), [data, slug, visible, featured, listed, authorized, authorizationDate, order]);
  const dirty = currentState !== initialState;
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  const close = () => { if (!dirty || window.confirm("Hay cambios sin guardar. ¿Cerrar igualmente?")) onClose(); };

  const update = (key: string, value: unknown) => setData((current) => ({ ...current, [key]: value }));
  async function save(close = true) {
    setSaving(true); setFeedback("");
    try {
      await cmsApi(`${record.collection}/${record.id}`, { method: "PUT", body: JSON.stringify({ data, slug: slug || null, visible, featured, listed, authorized, authorizationDate: authorizationDate || null, order, protected: record.protected }) });
      setFeedback("Borrador guardado."); await onReload(); if (close) await onSaved(); return true;
    } catch (error) { setFeedback(error instanceof Error ? error.message : "Revisa los campos."); return false; }
    finally { setSaving(false); }
  }
  async function publish() {
    if (!await save(false)) return;
    setSaving(true);
    try { await cmsApi(`${record.collection}/${record.id}/publish`, { method: "POST", body: "{}" }); setFeedback("Contenido publicado."); await onSaved(); }
    catch (error) { setFeedback(error instanceof Error ? error.message : "No se ha podido publicar."); }
    finally { setSaving(false); }
  }

  const mediaProps = { media, onUploaded: onReload };
  return <div className="admin-dialog-backdrop" role="presentation"><section className="admin-dialog" role="dialog" aria-modal="true" aria-labelledby="editor-title"><header><div><small>{labels[record.collection] ?? "Contenido"} · <StatusLabel record={record} visible={visible} /></small><h2 id="editor-title">{recordTitle({ ...record, draft: data })}</h2></div><button type="button" onClick={close} aria-label="Cerrar">×</button></header>
    {record.collection === "talents" && <TalentTabs active={activeTab} onChange={setActiveTab} />}
    <div className="admin-editor-body">
      {record.collection === "home" && <HomeEditor id={record.id} data={data} update={update} mediaProps={mediaProps} visible={visible} setVisible={setVisible} />}
      {record.collection === "talents" && <TalentEditor tab={activeTab} data={data} update={update} slug={slug} setSlug={setSlug} mediaProps={mediaProps} visible={visible} setVisible={setVisible} listed={listed} setListed={setListed} featured={featured} setFeatured={setFeatured} authorized={authorized} setAuthorized={setAuthorized} authorizationDate={authorizationDate} setAuthorizationDate={setAuthorizationDate} order={order} setOrder={setOrder} status={record.status} />}
      {record.collection === "news" && <NewsEditor data={data} update={update} slug={slug} setSlug={setSlug} mediaProps={mediaProps} visible={visible} setVisible={setVisible} featured={featured} setFeatured={setFeatured} />}
      {record.collection === "professionals" && <ProfessionalEditor data={data} update={update} mediaProps={mediaProps} visible={visible} setVisible={setVisible} order={order} setOrder={setOrder} protectedRecord={record.protected} />}
      {record.collection === "settings" && <SettingsEditor data={data} update={update} mediaProps={mediaProps} />}
      {record.collection === "media" && <MediaEditor data={data} update={update} visible={visible} setVisible={setVisible} />}
      {feedback && <p className={feedback.includes("guardado") || feedback.includes("publicado") ? "admin-success" : "admin-error"} role="status">{feedback}</p>}
    </div>
    <footer><button type="button" onClick={close}>Cancelar</button><button type="button" onClick={() => setPreview(true)}>Vista previa</button><button type="button" disabled={saving} onClick={() => void save()}>{saving ? "Guardando…" : "Guardar borrador"}</button>{record.collection !== "media" && <button className="is-primary" disabled={saving} type="button" onClick={() => void publish()}>Publicar</button>}</footer>
  </section>{preview && <PreviewDialog record={{ ...record, draft: data, slug }} onClose={() => setPreview(false)} />}</div>;
}

function StatusLabel({ record, visible }: { record: CmsRecord; visible: boolean }) { return <>{recordStateLabel(record)}{!visible ? " · Oculto" : ""}</>; }

function HomeEditor({ id, data, update, mediaProps, visible, setVisible }: { id: string; data: CmsData; update: (key: string, value: unknown) => void; mediaProps: { media: CmsRecord[]; onUploaded: () => Promise<void> }; visible: boolean; setVisible: (value: boolean) => void }) {
  const image = (key: string, label: string) => <ImagePicker label={label} value={imageSource(data[key])} onChange={(src) => update(key, withImageSource(data[key], src))} {...mediaProps} />;
  const common = <FieldGroup title="Publicación"><Switch label="Mostrar esta sección" checked={visible} onChange={setVisible} help="Puedes ocultarla sin borrar su contenido." /></FieldGroup>;
  if (id === "hero") return <>{common}<FieldGroup title="Portada" text="Edita el mensaje principal sin alterar su composición."><Field label="Descriptor" value={text(data.eyebrow)} onChange={(value) => update("eyebrow", value)} /><Field label="Titular" value={text(data.title)} onChange={(value) => update("title", value)} required /><Field label="Segunda línea" value={text(data.titleEmphasis)} onChange={(value) => update("titleEmphasis", value)} /><TextArea label="Introducción" value={text(data.body)} onChange={(value) => update("body", value)} /><Field label="Texto del botón principal" value={text(data.primaryButton)} onChange={(value) => update("primaryButton", value)} /><Field label="Enlace del botón principal" value={text(data.primaryHref)} onChange={(value) => update("primaryHref", value)} help="Usa una sección interna (#informacion) o una URL HTTPS." /><Field label="Texto del botón secundario" value={text(data.secondaryButton)} onChange={(value) => update("secondaryButton", value)} /><Field label="Enlace del botón secundario" value={text(data.secondaryHref)} onChange={(value) => update("secondaryHref", value)} help="Usa una sección interna (#en-sala) o una URL HTTPS." />{image("image", "Fotografía")}</FieldGroup></>;
  if (id === "master-dub") { const access = objectValue(data.access); return <>{common}<FieldGroup title="Presentación"><Field label="Nombre" value={text(data.name)} onChange={(value) => update("name", value)} /><Field label="Director" value={text(data.director)} onChange={(value) => update("director", value)} /><Field label="Antetítulo" value={text(data.eyebrow)} onChange={(value) => update("eyebrow", value)} /><Field label="Titular" value={text(data.headline)} onChange={(value) => update("headline", value)} required /><TextArea label="Introducción" value={text(data.introduction)} onChange={(value) => update("introduction", value)} /><TextArea label="Requisitos" value={text(data.eligibility)} onChange={(value) => update("eligibility", value)} />{image("image", "Fotografía principal")}{image("lanyard", "Fotografía secundaria")}</FieldGroup><ObjectList label="Datos de la experiencia" values={arrayValue(data.facts)} onChange={(value) => update("facts", value)} fields={[{ key: "label", label: "Etiqueta" }, { key: "value", label: "Valor" }]} /><FieldGroup title="Llamada a la acción"><Field label="Texto del botón" value={text(access.cta)} onChange={(value) => update("access", { ...access, cta: value })} /><Field label="Enlace" value={text(access.href)} onChange={(value) => update("access", { ...access, href: value })} /><Field label="Nota de disponibilidad" value={text(access.availability)} onChange={(value) => update("access", { ...access, availability: value })} /></FieldGroup><NestedEditorialGroups data={data} update={update} /></>; }
  if (id === "annual") { const facts = objectValue(data.facts); const setFact = (key: string, value: string) => update("facts", { ...facts, [key]: value }); return <>{common}<FieldGroup title="Formación Anual"><Field label="Antetítulo" value={text(data.kicker)} onChange={(value) => update("kicker", value)} /><Field label="Titular" value={text(data.title)} onChange={(value) => update("title", value)} required /><StringList label="Introducción" values={arrayValue<string>(data.lead)} onChange={(value) => update("lead", value)} /><TextArea label="Idea principal" value={text(data.purpose)} onChange={(value) => update("purpose", value)} />{image("image", "Fotografía")}</FieldGroup><StringList label="Principios" values={arrayValue<string>(data.principles)} onChange={(value) => update("principles", value)} /><FieldGroup title="Datos prácticos"><Field label="Calendario" value={text(facts.period)} onChange={(value) => setFact("period", value)} /><Field label="Ritmo" value={text(facts.weeklySchedule)} onChange={(value) => setFact("weeklySchedule", value)} /><Field label="Duración de la sesión" value={text(facts.classDuration)} onChange={(value) => setFact("classDuration", value)} /><Field label="Grupo" value={text(facts.groupSize)} onChange={(value) => setFact("groupSize", value)} /><Field label="Acceso" value={text(facts.access)} onChange={(value) => setFact("access", value)} /><Field label="Texto del botón" value={text(data.cta)} onChange={(value) => update("cta", value)} /><Field label="Enlace del botón" value={text(data.href)} onChange={(value) => update("href", value)} /></FieldGroup><StringList label="Áreas de trabajo" values={arrayValue<string>(data.areas)} onChange={(value) => update("areas", value)} /></>; }
  if (id === "facilities") return <>{common}<FieldGroup title="Instalaciones"><Field label="Antetítulo" value={text(data.eyebrow)} onChange={(value) => update("eyebrow", value)} /><Field label="Titular" value={text(data.title)} onChange={(value) => update("title", value)} /><TextArea label="Descripción" value={text(data.description)} onChange={(value) => update("description", value)} /><Field label="Colaboración" value={text(data.collaboration)} onChange={(value) => update("collaboration", value)} /></FieldGroup><ImageGallery label="Fotografías" values={arrayValue(data.images)} onChange={(value) => update("images", value)} {...mediaProps} /></>;
  if (id === "professionals") return <>{common}<FieldGroup title="Profesionales"><Field label="Titular" value={text(data.title)} onChange={(value) => update("title", value)} /><Field label="Título de profesionales invitados" value={text(data.invitedTitle)} onChange={(value) => update("invitedTitle", value)} /><TextArea label="Introducción de invitados" value={text(data.invitedIntroduction)} onChange={(value) => update("invitedIntroduction", value)} /></FieldGroup></>;
  if (id === "studio") return <>{common}<FieldGroup title="En Sala"><Field label="Antetítulo" value={text(data.kicker)} onChange={(value) => update("kicker", value)} /><Field label="Titular" value={text(data.title)} onChange={(value) => update("title", value)} /><TextArea label="Introducción" value={text(data.description)} onChange={(value) => update("description", value)} /></FieldGroup><ObjectList label="Módulos" values={arrayValue(data.videos)} onChange={(value) => update("videos", value)} fields={[{ key: "title", label: "Título" }, { key: "description", label: "Descripción" }, { key: "duration", label: "Duración" }, { key: "src", label: "URL de vídeo", type: "url" }, { key: "accessibilityLabel", label: "Descripción accesible", type: "textarea" }]} /></>;
  if (id === "talents") return <>{common}<FieldGroup title="Talentos"><Field label="Titular" value={text(data.title)} onChange={(value) => update("title", value)} /><TextArea label="Introducción" value={text(data.body)} onChange={(value) => update("body", value)} /><Field label="Texto del botón" value={text(data.button)} onChange={(value) => update("button", value)} /></FieldGroup></>;
  if (id === "news") return <>{common}<FieldGroup title="Noticias"><Field label="Titular" value={text(data.title)} onChange={(value) => update("title", value)} /><TextArea label="Introducción" value={text(data.body)} onChange={(value) => update("body", value)} /></FieldGroup></>;
  if (id === "information") return <>{common}<FieldGroup title="Información y contacto"><Field label="Antetítulo" value={text(data.kicker)} onChange={(value) => update("kicker", value)} /><Field label="Titular" value={text(data.title)} onChange={(value) => update("title", value)} /><TextArea label="Introducción" value={text(data.body)} onChange={(value) => update("body", value)} /></FieldGroup></>;
  return <>{common}<FieldGroup title="Footer"><Field label="Descriptor" value={text(data.descriptor)} onChange={(value) => update("descriptor", value)} /><Field label="Firma" value={text(data.signature)} onChange={(value) => update("signature", value)} /><Field label="Email" type="email" value={text(data.email)} onChange={(value) => update("email", value)} /></FieldGroup></>;
}

function NestedEditorialGroups({ data, update }: { data: CmsData; update: (key: string, value: unknown) => void }) {
  const groups = [
    ["preparation", "Preparación", "criteria"], ["work", "Durante la experiencia", "dynamics"], ["direction", "Dirección", ""], ["outcome", "Al finalizar", "assessment"],
  ] as const;
  return <>{groups.map(([key, title, listKey]) => { const group = objectValue(data[key]); const set = (field: string, value: unknown) => update(key, { ...group, [field]: value }); return <FieldGroup key={key} title={title}><Field label="Antetítulo" value={text(group.eyebrow)} onChange={(value) => set("eyebrow", value)} /><Field label="Titular" value={text(group.title)} onChange={(value) => set("title", value)} /><TextArea label="Descripción" value={text(group.description)} onChange={(value) => set("description", value)} />{listKey && <StringList label="Puntos" values={arrayValue<string>(group[listKey])} onChange={(value) => set(listKey, value)} />}{key === "preparation" && <TextArea label="Principio" value={text(group.principle)} onChange={(value) => set("principle", value)} />}{key === "work" && <><TextArea label="Adaptación del material" value={text(group.adaptation)} onChange={(value) => set("adaptation", value)} /><StringList label="Formatos" values={arrayValue<string>(group.genres)} onChange={(value) => set("genres", value)} /></>}{key === "outcome" && <><Field label="Acreditación" value={text(group.accreditation)} onChange={(value) => set("accreditation", value)} /><TextArea label="Nota de oyente" value={text(group.observerNote)} onChange={(value) => set("observerNote", value)} /><TextArea label="Aclaración" value={text(group.disclaimer)} onChange={(value) => set("disclaimer", value)} /></>}</FieldGroup>; })}</>;
}

const talentTabs = [["profile","Perfil"],["voice","Voz"],["training","Formación"],["demos","Demos"],["videos","Vídeos"],["credits","Trabajos"],["gallery","Galería"],["contact","Contacto"],["design","Diseño"],["seo","SEO"]] as const;
function TalentTabs({ active, onChange }: { active: string; onChange: (tab: string) => void }) { return <div className="admin-editor-tabs" role="tablist" aria-label="Áreas del perfil">{talentTabs.map(([id,label]) => <button type="button" role="tab" aria-selected={active === id} className={active === id ? "is-active" : ""} onClick={() => onChange(id)} key={id}>{label}</button>)}</div>; }

type TalentProps = { tab: string; data: CmsData; update: (key: string, value: unknown) => void; slug: string; setSlug: (value: string) => void; mediaProps: { media: CmsRecord[]; onUploaded: () => Promise<void> }; visible: boolean; setVisible: (value: boolean) => void; listed: boolean; setListed: (value: boolean) => void; featured: boolean; setFeatured: (value: boolean) => void; authorized: boolean; setAuthorized: (value: boolean) => void; authorizationDate: string; setAuthorizationDate: (value: string) => void; order: number; setOrder: (value: number) => void; status: string };
function TalentEditor(props: TalentProps) {
  const { tab, data, update, mediaProps } = props;
  if (tab === "profile") return <><FieldGroup title="Identidad profesional"><Field label="Nombre completo" value={text(data.name)} onChange={(value) => { update("name", value); if (!props.slug) props.setSlug(slugify(value)); }} required /><Field label="Nombre artístico" value={text(data.stageName)} onChange={(value) => update("stageName", value)} /><Field label="Dirección pública" value={props.slug} onChange={(value) => props.setSlug(slugify(value))} help={`masterdub.es/${props.slug || "nombre"}`} /><Field label="Ubicación" value={text(data.location)} onChange={(value) => update("location", value)} /><Field label="Titular profesional" value={text(data.professionalTitle)} onChange={(value) => update("professionalTitle", value)} /><TextArea label="Introducción" value={text(data.introduction)} onChange={(value) => update("introduction", value)} /><TextArea label="Biografía" rows={8} value={text(data.biography)} onChange={(value) => update("biography", value)} /></FieldGroup><FieldGroup title="Imágenes"><ImagePicker label="Fotografía principal" value={text(data.photo)} onChange={(value) => update("photo", value)} {...mediaProps} /><Field label="Descripción accesible de la fotografía" value={text(data.photoAlt)} onChange={(value) => update("photoAlt", value)} /><ImagePicker label="Imagen de fondo" value={text(data.backgroundImage)} onChange={(value) => update("backgroundImage", value)} {...mediaProps} /></FieldGroup><PublicationBlocks {...props} /></>;
  if (tab === "voice") return <FieldGroup title="Perfil de voz"><TextArea label="Características de voz" value={text(data.voiceCharacteristics)} onChange={(value) => update("voiceCharacteristics", value)} /><Field label="Rango de edad vocal / interpretativa" value={text(data.voiceAgeRange)} onChange={(value) => update("voiceAgeRange", value)} /><StringList label="Idiomas" values={arrayValue<string>(data.languages)} onChange={(value) => update("languages", value)} /><StringList label="Acentos" values={arrayValue<string>(data.accents)} onChange={(value) => update("accents", value)} /><StringList label="Especialidades" values={arrayValue<string>(data.specialties)} onChange={(value) => update("specialties", value)} /></FieldGroup>;
  if (tab === "training") return <ObjectList label="Formación" values={normalizeObjects(data.training, "center")} onChange={(value) => update("training", value)} fields={[{ key: "center", label: "Centro / formación" }, { key: "description", label: "Descripción", type: "textarea" }, { key: "dates", label: "Fechas (opcional)" }]} />;
  if (tab === "demos") return <><ObjectList label="Demos externas" values={arrayValue(data.demos)} onChange={(value) => update("demos", value)} fields={[{ key: "title", label: "Título" }, { key: "url", label: "URL", type: "url" }, { key: "category", label: "Tipo / categoría" }, { key: "description", label: "Descripción", type: "textarea" }, { key: "visible", label: "Visible", type: "checkbox" }]} /><ExternalReuse kind="audio" media={mediaProps.media} onAdd={(item)=>update("demos",[...arrayValue(data.demos),item])} /></>;
  if (tab === "videos") return <><ObjectList label="Vídeos externos" values={arrayValue(data.videos)} onChange={(value) => update("videos", value)} fields={[{ key: "title", label: "Título" }, { key: "url", label: "URL de YouTube, Vimeo o compatible", type: "url" }, { key: "category", label: "Categoría" }, { key: "description", label: "Descripción", type: "textarea" }, { key: "visible", label: "Visible", type: "checkbox" }]} /><ExternalReuse kind="video" media={mediaProps.media} onAdd={(item)=>update("videos",[...arrayValue(data.videos),item])} /><ExternalPreviewList values={arrayValue(data.videos)} /></>;
  if (tab === "credits") return <ObjectList label="Trabajos" values={normalizeObjects(data.credits, "title")} onChange={(value) => update("credits", value)} fields={[{ key: "title", label: "Título" }, { key: "project", label: "Producción / proyecto" }, { key: "role", label: "Personaje / función" }, { key: "year", label: "Año" }, { key: "description", label: "Descripción", type: "textarea" }, { key: "url", label: "Enlace", type: "url" }]} />;
  if (tab === "gallery") return <ImageGallery label="Galería" values={arrayValue(data.gallery)} onChange={(value) => update("gallery", value)} {...mediaProps} />;
  if (tab === "contact") return <ContactEditor data={data} update={update} />;
  if (tab === "design") return <DesignEditor data={data} update={update} mediaProps={mediaProps} />;
  return <FieldGroup title="SEO y vista al compartir"><Field label="SEO title" value={text(data.seoTitle)} onChange={(value) => update("seoTitle", value)} /><TextArea label="Meta description" value={text(data.seoDescription)} onChange={(value) => update("seoDescription", value)} help="Recomendación: 140–160 caracteres." /><Field label="Dirección canónica" value={`https://masterdub.es/${props.slug || "nombre"}`} onChange={() => undefined} help="Se genera automáticamente a partir de la dirección pública." /><ImagePicker label="Imagen social" value={text(data.socialImage)} onChange={(value) => update("socialImage", value)} {...mediaProps} /><SharePreview title={text(data.seoTitle) || text(data.stageName) || text(data.name)} description={text(data.seoDescription) || text(data.introduction)} image={text(data.socialImage) || text(data.photo)} /></FieldGroup>;
}

function normalizeObjects(value: unknown, key: string) { return arrayValue<unknown>(value).map((item) => typeof item === "string" ? { [key]: item } : objectValue(item)); }
function PublicationBlocks(props: TalentProps) { return <><FieldGroup title="Publicación" text="Estos controles determinan dónde aparece el perfil."><Switch label="Perfil publicado" checked={props.visible} onChange={props.setVisible} /><Switch label="Mostrar en Talentos" checked={props.listed} onChange={props.setListed} /><Switch label="Destacar en Home" checked={props.featured} onChange={props.setFeatured} /><Field label="Orden" type="number" value={props.order} onChange={(value) => props.setOrder(Number(value) || 0)} /></FieldGroup><FieldGroup title="Autorización de publicación" text="Información interna. Nunca se muestra en el perfil público."><Switch label="Autorización registrada" checked={props.authorized} onChange={props.setAuthorized} /><Field label="Fecha de autorización" type="date" value={props.authorizationDate} onChange={props.setAuthorizationDate} />{props.slug && <TalentQr slug={props.slug} />}</FieldGroup></>; }

function TalentQr({ slug }: { slug: string }) { const [png, setPng] = useState(""); const [svg, setSvg] = useState(""); useEffect(() => { let active = true; const url = `https://masterdub.es/${slug}`; void Promise.all([QRCode.toDataURL(url, { width: 420, margin: 2, color: { dark: "#11120f", light: "#ffffff" } }), QRCode.toString(url, { type: "svg", margin: 2, color: { dark: "#11120f", light: "#ffffff" } })]).then(([pngValue, svgValue]) => { if (active) { setPng(pngValue); setSvg(`data:image/svg+xml;charset=utf-8,${encodeURIComponent(svgValue)}`); } }); return () => { active = false; }; }, [slug]); return <div className="admin-qr"><div>{png ? <img src={png} alt={`QR de masterdub.es/${slug}`} /> : <span>Generando QR…</span>}</div><p>masterdub.es/{slug}</p>{png && <a href={png} download={`masterdub-${slug}-qr.png`}>Descargar PNG</a>}{svg && <a href={svg} download={`masterdub-${slug}-qr.svg`}>Descargar SVG</a>}</div>; }

function ContactEditor({ data, update }: { data: CmsData; update: (key: string, value: unknown) => void }) {
  const contact = objectValue(data.contact); const fields = [["email","Email","email"],["phone","Teléfono","tel"],["instagram","Instagram","url"],["linkedin","LinkedIn","url"],["website","Web","url"]] as const;
  const get = (key: string) => { const raw = contact[key]; return typeof raw === "string" ? { value: raw, visible: false } : { value: text(objectValue(raw).value), visible: bool(objectValue(raw).visible) }; };
  const set = (key: string, field: "value" | "visible", value: string | boolean) => update("contact", { ...contact, [key]: { ...get(key), [field]: value } });
  return <FieldGroup title="Contacto profesional" text="Nada se publica automáticamente. Activa cada dato de forma expresa.">{fields.map(([key,label,type]) => { const item = get(key); return <div className="admin-contact-row" key={key}><Field label={label} type={type} value={item.value} onChange={(value) => set(key,"value",value)} /><Switch label="Mostrar públicamente" checked={item.visible} onChange={(value) => set(key,"visible",value)} /></div>; })}<ObjectList label="Otros enlaces" values={arrayValue(contact.other)} onChange={(value) => update("contact", { ...contact, other: value })} fields={[{ key: "label", label: "Nombre" }, { key: "value", label: "URL", type: "url" }, { key: "visible", label: "Mostrar públicamente", type: "checkbox" }]} /></FieldGroup>;
}

function DesignEditor({ data, update, mediaProps }: { data: CmsData; update: (key: string, value: unknown) => void; mediaProps: { media: CmsRecord[]; onUploaded: () => Promise<void> } }) { const template = text(data.template) || "editorial"; return <><FieldGroup title="Plantilla"><div className="admin-template-grid">{[["cinema","01","CINEMA"],["editorial","02","EDITORIAL"],["studio","03","STUDIO"]].map(([id,number,label]) => <button type="button" className={template === id ? "is-active" : ""} onClick={() => update("template",id)} key={id}><span>{number}</span><strong>{label}</strong><i className={`admin-template-${id}`} /></button>)}</div></FieldGroup><FieldGroup title="Composición"><ImagePicker label="Imagen de fondo" value={text(data.backgroundImage)} onChange={(value) => update("backgroundImage", value)} {...mediaProps} /><ImagePicker label="Foto principal" value={text(data.photo)} onChange={(value) => update("photo", value)} {...mediaProps} /><SelectField label="Posición de la foto" value={text(data.photoPosition) || "center"} onChange={(value) => update("photoPosition", value)}><option value="center">Centrada</option><option value="center top">Arriba</option><option value="center 35%">Rostro alto</option><option value="center 45%">Rostro centrado</option><option value="left center">A la izquierda</option><option value="right center">A la derecha</option></SelectField><label className="admin-range"><span>Oscuridad del fondo</span><input type="range" min="0" max="0.85" step="0.05" value={numberValue(data.backgroundIntensity,.58)} onChange={(event) => update("backgroundIntensity",Number(event.target.value))} /><b>{Math.round(numberValue(data.backgroundIntensity,.58)*100)}%</b></label><ImagePicker label="Imagen social" value={text(data.socialImage)} onChange={(value) => update("socialImage", value)} {...mediaProps} /></FieldGroup></>; }

function NewsEditor({ data, update, slug, setSlug, mediaProps, visible, setVisible, featured, setFeatured }: { data: CmsData; update: (key: string, value: unknown) => void; slug: string; setSlug: (value: string) => void; mediaProps: { media: CmsRecord[]; onUploaded: () => Promise<void> }; visible: boolean; setVisible: (value: boolean) => void; featured: boolean; setFeatured: (value: boolean) => void }) { return <><FieldGroup title="Publicación"><Field label="Título" value={text(data.title)} onChange={(value) => { update("title", value); if (!slug) setSlug(slugify(value)); }} required /><Field label="Dirección pública" value={slug} onChange={(value) => setSlug(slugify(value))} help={`masterdub.es/noticias/${slug || "titulo"}`} /><Field label="Fecha" type="date" value={text(data.date)} onChange={(value) => update("date", value)} /><Field label="Autor (opcional)" value={text(data.author)} onChange={(value) => update("author", value)} /><Switch label="Visible" checked={visible} onChange={setVisible} /><Switch label="Destacada en Home" checked={featured} onChange={setFeatured} /></FieldGroup><FieldGroup title="Contenido"><TextArea label="Introducción" value={text(data.introduction)} onChange={(value) => update("introduction", value)} rows={4} /><TextArea label="Cuerpo" value={text(data.body)} onChange={(value) => update("body", value)} rows={14} help="Separa los párrafos con una línea en blanco." /><ImagePicker label="Imagen de portada" value={text(data.coverImage)} onChange={(value) => update("coverImage", value)} {...mediaProps} /><Field label="Descripción accesible de la portada" value={text(data.coverAlt)} onChange={(value) => update("coverAlt", value)} /></FieldGroup><ImageGallery label="Galería opcional" values={arrayValue(data.gallery)} onChange={(value) => update("gallery", value)} {...mediaProps} /><FieldGroup title="SEO"><Field label="SEO title" value={text(data.seoTitle)} onChange={(value) => update("seoTitle", value)} /><TextArea label="Meta description" value={text(data.seoDescription)} onChange={(value) => update("seoDescription", value)} /><ImagePicker label="Imagen social" value={text(data.socialImage)} onChange={(value) => update("socialImage", value)} {...mediaProps} /><SharePreview title={text(data.seoTitle) || text(data.title)} description={text(data.seoDescription) || text(data.introduction)} image={text(data.socialImage) || text(data.coverImage)} /></FieldGroup></>; }

function ProfessionalEditor({ data, update, mediaProps, visible, setVisible, order, setOrder, protectedRecord }: { data: CmsData; update: (key: string, value: unknown) => void; mediaProps: { media: CmsRecord[]; onUploaded: () => Promise<void> }; visible: boolean; setVisible: (value: boolean) => void; order: number; setOrder: (value: number) => void; protectedRecord: boolean }) { const website = objectValue(data.website); return <><FieldGroup title="Perfil"><Field label="Nombre" value={text(data.name)} onChange={(value) => update("name", value)} required /><Field label="Rol / cargo" value={text(data.role)} onChange={(value) => update("role", value)} /><TextArea label="Descripción" value={text(data.introduction)} onChange={(value) => update("introduction", value)} /><ImagePicker label="Fotografía" value={text(data.photo)} onChange={(value) => update("photo", value)} {...mediaProps} /><Field label="Descripción accesible de la foto" value={text(data.photoAlt)} onChange={(value) => update("photoAlt", value)} /><Field label="Nombre del enlace principal" value={text(website.label)} onChange={(value) => update("website",{ ...website,label:value })} /><Field label="Enlace principal" type="url" value={text(website.href)} onChange={(value) => update("website",{ ...website,href:value })} /></FieldGroup><ObjectList label="Enlaces adicionales" values={arrayValue(data.links)} onChange={(value) => update("links", value)} fields={[{ key: "label", label: "Nombre" }, { key: "href", label: "URL", type: "url" }]} /><FieldGroup title="Publicación"><Switch label="Visible" checked={visible} onChange={setVisible} /><Field label="Orden" type="number" value={order} onChange={(value) => setOrder(Number(value)||0)} />{protectedRecord && <p className="admin-protected-note">Perfil estable protegido frente a eliminación accidental.</p>}</FieldGroup></>; }

function SettingsEditor({ data, update, mediaProps }: { data: CmsData; update: (key: string, value: unknown) => void; mediaProps: { media: CmsRecord[]; onUploaded: () => Promise<void> } }) { return <><FieldGroup title="Identidad"><Field label="Nombre del sitio" value={text(data.name)} onChange={(value) => update("name",value)} /><Field label="Descriptor" value={text(data.descriptor)} onChange={(value) => update("descriptor",value)} /><Field label="Lema accesible de marca" value={text(data.strapline)} onChange={(value) => update("strapline",value)} /><ImagePicker label="Logo" value={text(data.logo)} onChange={(value) => update("logo",value)} {...mediaProps} /><Field label="Email" type="email" value={text(data.email)} onChange={(value) => update("email",value)} /><Field label="Teléfono" type="tel" value={text(data.phone)} onChange={(value) => update("phone",value)} /><TextArea label="Dirección" value={text(data.address)} onChange={(value) => update("address",value)} /></FieldGroup><FieldGroup title="Redes"><Field label="Instagram" type="url" value={text(data.instagram)} onChange={(value) => update("instagram",value)} /><Field label="TikTok" type="url" value={text(data.tiktok)} onChange={(value) => update("tiktok",value)} /><Field label="YouTube" type="url" value={text(data.youtube)} onChange={(value) => update("youtube",value)} /></FieldGroup><FieldGroup title="SEO general"><Field label="SEO title" value={text(data.seoTitle)} onChange={(value) => update("seoTitle",value)} /><TextArea label="Meta description" value={text(data.seoDescription)} onChange={(value) => update("seoDescription",value)} /><ImagePicker label="Imagen social predeterminada" value={text(data.socialImage)} onChange={(value) => update("socialImage",value)} {...mediaProps} /><SharePreview title={text(data.seoTitle)} description={text(data.seoDescription)} image={text(data.socialImage)} /></FieldGroup></>; }

function MediaEditor({ data, update, visible, setVisible }: { data: CmsData; update: (key: string, value: unknown) => void; visible: boolean; setVisible: (value: boolean) => void }) { const kind = text(data.kind) || "image"; return <FieldGroup title={kind === "image" ? "Datos de la imagen" : "Datos del contenido externo"}><Field label="Nombre" value={text(data.name) || text(data.title)} onChange={(value) => { update("name",value); update("title",value); }} /><Field label="Texto alternativo" value={text(data.alt)} onChange={(value) => update("alt",value)} help={kind === "image" ? "Describe la imagen cuando aporte información." : undefined} />{kind !== "image" && <><Field label="URL" type="url" value={text(data.url)} onChange={(value) => update("url",value)} /><Field label="Categoría" value={text(data.category)} onChange={(value) => update("category",value)} /><TextArea label="Descripción" value={text(data.description)} onChange={(value) => update("description",value)} /></>}<Switch label="Visible" checked={visible} onChange={setVisible} /></FieldGroup>; }

function ImageGallery({ label, values, onChange, media, onUploaded }: { label: string; values: unknown[]; onChange: (value: unknown[]) => void; media: CmsRecord[]; onUploaded: () => Promise<void> }) { const normalized = values.map((value) => typeof value === "string" ? value : imageSource(value)); const move = (index: number, direction: -1|1) => { const target=index+direction;if(target<0||target>=normalized.length)return;const next=[...normalized];[next[index],next[target]]=[next[target],next[index]];onChange(next);}; return <div className="admin-repeater"><div className="admin-repeater-heading"><strong>{label}</strong><button type="button" onClick={() => onChange([...normalized,""])}>＋ Añadir imagen</button></div>{normalized.map((value,index) => <article className="admin-gallery-row" key={index}><ImagePicker label={`Imagen ${index+1}`} value={value} onChange={(src) => onChange(normalized.map((item,itemIndex)=>itemIndex===index?src:item))} media={media} onUploaded={onUploaded} /><footer><button type="button" disabled={index===0} onClick={()=>move(index,-1)}>↑ Subir</button><button type="button" disabled={index===normalized.length-1} onClick={()=>move(index,1)}>↓ Bajar</button><button type="button" className="is-danger" onClick={()=>onChange(normalized.filter((_,itemIndex)=>itemIndex!==index))}>Quitar</button></footer></article>)}{normalized.length===0&&<p className="admin-empty-small">Todavía no hay imágenes.</p>}</div>; }

function ExternalPreviewList({ values }: { values: Array<Record<string,unknown>> }) { const first = values.find((item)=>text(item.url)); return first ? <FieldGroup title="Previsualización" text="El reproductor no se conecta hasta que pulses."><ExternalMedia url={text(first.url)} title={text(first.title)||"Vídeo"} /></FieldGroup> : null; }
function ExternalReuse({ kind, media, onAdd }: { kind: "video"|"audio"; media: CmsRecord[]; onAdd: (item: Record<string,unknown>)=>void }) { const options=media.filter((record)=>text(record.draft.kind)===kind&&text(record.draft.url)); if(!options.length)return null; return <FieldGroup title={`Reutilizar ${kind === "video" ? "vídeo" : "audio"} de Multimedia`} text="Añade un enlace ya registrado sin volver a copiarlo."><div className="admin-external-reuse">{options.map((record)=><button type="button" key={record.id} onClick={()=>onAdd({title:text(record.draft.title)||text(record.draft.name),url:text(record.draft.url),category:text(record.draft.category),description:text(record.draft.description),visible:true})}><span>{kind === "video" ? "▶" : "♪"}</span><strong>{text(record.draft.title)||text(record.draft.name)}</strong><small>{text(record.draft.provider)}</small></button>)}</div></FieldGroup>; }
function SharePreview({ title, description, image }: { title: string; description: string; image: string }) { return <div className="admin-share-preview">{image &&   <img src={image} alt="" />}<div><small>masterdub.es</small><strong>{title || "Título de la página"}</strong><p>{description || "La descripción aparecerá aquí."}</p></div></div>; }

function PreviewDialog({ record, onClose }: { record: CmsRecord; onClose: () => void }) { const url = record.collection === "talents" && record.slug ? `/${record.slug}` : record.collection === "news" && record.slug ? `/noticias/${record.slug}` : record.collection === "home" ? `/#${record.id}` : "/"; return <div className="admin-preview-backdrop"><section className="admin-preview-dialog"><header><div><small>Vista previa del contenido</small><h3>{recordTitle(record)}</h3></div><button type="button" onClick={onClose}>×</button></header><div>{Boolean(record.draft.photo) && <img src={imageSource(record.draft.photo)} alt="" />}<p>{text(record.draft.introduction)||text(record.draft.body)||text(record.draft.description)||"Revisa el contenido y publícalo cuando esté listo."}</p><dl><div><dt>Estado</dt><dd>{record.status === "published" ? "Publicado" : "Borrador"}</dd></div><div><dt>Visibilidad</dt><dd>{record.visible ? "Visible" : "Oculto"}</dd></div></dl></div>{record.status === "published" && <a href={url} target="_blank" rel="noreferrer">Abrir página pública ↗</a>}</section></div>; }
